### ISSUE TITLE
Using Proxies on Chromedriver

### ISSUE THREAD

**Issue by gerimo** [dimmg/dockselpy#4]
Hi Dim! Why do you think I can't connect using proxies?

```
def selenium_connect():
        PROXY = "66.97.38.58:80"
        url = "http://whatsmyip.org"
        chrome_options = webdriver.ChromeOptions()
        chrome_options.add_argument('--headless')
        chrome_options.add_argument('--no-sandbox')
        chrome_options.add_argument('--disable-dev-shm-usage')
        chrome_options.add_argument('--proxy-server=%s' % PROXY)
        driver = webdriver.Chrome(chrome_options=chrome_options)
        driver.get(url)
```

Been struggling with these and can't seem to find a way.

**Comment by gerimo** [comment]
Dim, can I pay you 100USD via paypal for you to configure my luminati proxies on Selenium?

https://github.com/gerimo/challenge

**Comment by dimmg** [comment]
Hi @gerimo ,

AFAIK there isn't an easy way to use proxy authentication on Selenium, it can be done by loading external extensions or trying other hard working actions.

What you can try instead:
- configure the proxy system wide: in this case all traffic will go through the specified proxy https://unix.stackexchange.com/questions/213737/how-do-i-set-systemwide-connection-over-a-proxy-server
- configure Docker to use a proxy server. More details on how to do this see here https://docs.docker.com/network/proxy/

Hope this solves your problem!

**Comment by gerimo** [comment]
It's hard because I'm using a proxy with authentification. 

If we were to configure a proxy like this for chromedriver on that simple docker container (using an extension for example).

Would build it and share it for USD200?

**Comment by dimmg** [comment]
Hi @gerimo ,

as I've said previously you can configure the docker container to use a proxy server.
To achieve this, you should simply pass several additional environment variables when starting the container.

How exactly to do this: 
```
export DOCKER_PROXY='http://username:password@host:port' && \
       docker run --env HTTP_PROXY=$DOCKER_PROXY --env HTTPS_PROXY=$DOCKER_PROXY -d <image_name>
```
Now in your container remove everything related to proxy, as it should be automatically used by the container.

If you still fail to succeed, feel free to reach me via email and close the issue!

Regards
